services:
  # Frontend Next.js
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: alertrace_frontend
    ports:
      - "3000:8080"
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL:-http://localhost:8002}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    env_file:
      - .env
    restart: unless-stopped
